message(STATUS "searching for flextool...")
find_package(flextool MODULE REQUIRED)

if(LOCAL_BUILD)
  get_property(flextool_location TARGET flextool PROPERTY RUNTIME_OUTPUT_DIRECTORY)
  message (STATUS "flextool_location == ${flextool_location}")
  set(flextool "${flextool_location}/flextool")
  message (STATUS "flextool == ${flextool}")
else()
  find_program(flextool flextool NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH)
  message(STATUS "find_program for flextool ${flextool}")
endif()
if(NOT flextool OR ${flextool} STREQUAL "")
  message(FATAL_ERROR "flextool not found ${flextool}")
endif()
